In [1]:
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import json

# # reading csv file 

location=  pd.read_csv('C:/Users/aleja/OneDrive/Bootcamp/projects/project-2/csv files/locationsV2.csv')
print(location)
observations=  pd.read_csv('C:/Users/aleja/OneDrive/Bootcamp/projects/project-2/csv files/peds_dataV2.csv')
observations

    SensorID                               Sensor   latitude   longitude
0          0           Bourke Street Mall (North) -37.813410  144.965225
1          1           Bourke Street Mall (South) -37.813723  144.965150
2          2                    Melbourne Central -37.810185  144.962801
3          3                     Town Hall (West) -37.814953  144.966194
4          4                       Princes Bridge -37.818819  144.967994
..       ...                                  ...        ...         ...
71        71       Bourke St - Spencer St (South) -37.816856  144.954069
72        72       Spring St - Flinders St (West) -37.815210  144.974777
73        73             Macaulay Rd - Bellair St -37.794268  144.930493
74        74  Harbour Esplanade - Pedestrian Path -37.814285  144.944280
75        75        Harbour Esplanade - Bike Path -37.814883  144.944532

[76 rows x 4 columns]

,Unnamed: 0,Sensor,Midnight,1am,2am,3am,4am,5am,6am,7am,...,5pm,6pm,7pm,8pm,9pm,10pm,11pm,dailyTotal,avgDaily,data_date
0,0,Bourke Street Mall (North),88.0,34.0,22.0,7.0,10.0,36.0,111.0,330.0,...,3683.0,3013.0,2001.0,1508.0,795.0,420.0,183.0,32841,1368.375,1/08/2019
1,1,Bourke Street Mall (South),24.0,6.0,12.0,9.0,2.0,7.0,67.0,192.0,...,1765.0,1353.0,753.0,607.0,289.0,103.0,6.0,18174,757.250,1/08/2019
2,2,Melbourne Central,241.0,143.0,73.0,35.0,34.0,108.0,163.0,332.0,...,2977.0,2965.0,2174.0,2046.0,1762.0,1142.0,570.0,30402,1266.750,1/08/2019
3,3,Town Hall (West),97.0,42.0,30.0,15.0,32.0,77.0,192.0,489.0,...,3326.0,2769.0,1802.0,1332.0,1096.0,593.0,322.0,32415,1350.625,1/08/2019
4,4,Princes Bridge,112.0,43.0,16.0,29.0,63.0,116.0,385.0,944.0,...,3195.0,2143.0,1338.0,1026.0,886.0,772.0,334.0,27108,1129.500,1/08/2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4707,71,Bourke St - Spencer St (South),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,31/08/2020
4708,72,Spring St - Flinders St (West),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,31/08/2020
4709,73,Macaulay Rd - Bellair St,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,31/08/2020
4710,74,Harbour Esplanade - Pedestrian Path,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,31/08/2020
4711,75,Harbour Esplanade - Bike Path,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,31/08/2020

In [2]:
newdf = pd.merge(
    location, 
    observations, 
    left_on=['Sensor'],
    right_on=['Sensor'])

In [3]:
newdf.reset_index()
newdf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4712 entries, 0 to 4711
Data columns (total 32 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SensorID    4712 non-null   int64
 1   Sensor      4712 non-null   object
 2   latitude    4712 non-null   float64
 3   longitude   4712 non-null   float64
 4   Unnamed: 0  4712 non-null   int64
 5   Midnight    3038 non-null   float64
 6   1am         2807 non-null   float64
 7   2am         2751 non-null   float64
 8   3am         2775 non-null   float64
 9   4am         2911 non-null   float64
 10  5am         3255 non-null   float64
 11  6am         3428 non-null   float64
 12  7am         3470 non-null   float64
 13  8am         3478 non-null   float64
 14  9am         3479 non-null   float64
 15  10am        3479 non-null   float64
 16  11am        3477 non-null   float64
 17  Noon        3475 non-null   float64
 18  1pm         3481 non-null   float64
 19  2pm         3490 non-null   float64
 20  3pm         3490 non-null   float64
 21  4pm         3488 non-null   float64
 22  5pm         3490 non-null   float64
 23  6pm         3463 non-null   float64
 24  7pm         3453 non-null   float64
 25  8pm         3415 non-null   float64
 26  9pm         3378 non-null   float64
 27  10pm        3241 non-null   float64
 28  11pm        3145 non-null   float64
 29  dailyTotal  4712 non-null   int64
 30  avgDaily    3512 non-null   float64
 31  data_date   4712 non-null   object
dtypes: float64(27), int64(3), object(2)
memory usage: 1.2+ MB

In [4]:
def df_to_geojson(df, properties, lat='latitude', lon='longitude'):
    print (properties)
    # create a new python dict to contain our geojson data, using geojson format
    geojson = {'type':'FeatureCollection', 'features':[]}

    # loop through each row in the dataframe and convert each row to geojson format
    for _, row in df.iterrows():
        # create a feature template to fill in
        feature = {'type':'Feature',
                   'properties':{},
                   'geometry':{'type':'Point',
                               'coordinates':[]}}

        # fill in the coordinates
        feature['geometry']['coordinates'] = [row[lon],row[lat]]

        # for each column, get the value and add it as a new feature property
        for prop in properties:
            feature['properties'][prop] = row[prop]
        geojson['features'].append(feature)
        
    return geojson

cols = ['Sensor','SensorID','Midnight','1am','2am','3am','4am','5am','6am','7am','8am','9am','10am','11am','Noon','1pm','2pm','3pm','4pm','5pm','6pm','7pm','8pm','9pm','10pm','11pm','dailyTotal','avgDaily','data_date']
geojson = df_to_geojson(newdf, cols)

['Sensor', 'SensorID', 'Midnight', '1am', '2am', '3am', '4am', '5am', '6am', '7am', '8am', '9am', '10am', '11am', 'Noon', '1pm', '2pm', '3pm', '4pm', '5pm', '6pm', '7pm', '8pm', '9pm', '10pm', '11pm', 'dailyTotal', 'avgDaily', 'data_date']

In [5]:
geo_json_list = []
for i in geojson:
   #code to generate your geoJSON
   geo_json_list.append(geojson)
with open('C:/Users/aleja/OneDrive/Bootcamp/projects/project-2/csv files/data2.geojson', 'a') as f:
    json.dump(geo_json_list, f)